### ISSUE TITLE
Going back to the Boards list sometimes doesn't show my boards.

### ISSUE THREAD

**Issue by VagishVela** [InsanityOnABun/GameRaven-old#19]
The application seems to update the board list when it is visited (which means that sometimes it doesn't show my boards).

Maybe allowing the board list to be cached, and only updating the topic/message counter?

**Comment by InsanityOnABun** [comment]
I'm not sure I follow. What part of the board list isn't being displayed?
Are there any steps you could provide to reproduce this? Are you navigating
to the board list, or refreshing it? If you're refreshing it, are you
manually refreshing it, or is it refreshing when you resume the app?

**Comment by VagishVela** [comment]
Sorry I wasn't being clear enough. It defaults to the logged out profile when I open the app after not using for a while.

**Comment by InsanityOnABun** [comment]
Ah. If you go to Settings -> Manage Account, and click on one of the accounts you have added, there is a check box to set it as the default account. The app will then log into that account whenever it starts up for the first time or after the operating system kills it. For now that's the only option to stay logged in even after the operating system kills the app, but better handling of and persistence through the app getting killed is on my to-do list.
