### ISSUE TITLE
New sig options are breaking post layout

### ISSUE THREAD

**Issue by starks** [InsanityOnABun/GameRaven-old#28]
http://www.gamefaqs.com/boards/6-gamefaqs-announcements/73683766
http://i.imgur.com/qc17JHz.png

**Comment by InsanityOnABun** [comment]
http://www.gamefaqs.com/boards/400-current-events/73684091
Will be working on a fix tonight.

**Comment by InsanityOnABun** [comment]
Fixed in 3cf7a1e
